using System;

namespace download_sam
{
    /// <summary>
    /// Contains global methods and fields
    /// </summary>

    class Globals
    {
        /// <summary>
        /// Copyright notice for the utility
        /// </summary>

        public static string Copyright = "Copyright 2020, Eric Ace";

        /// <summary>
        /// The instance of the logger for the utility
        /// </summary>

        public static MyLogger Log = new MyLogger();

        /// <summary>
        /// The implementation of application settgs functionality for the utility
        /// </summary>

        public static AppSettingsImpl cfg = new AppSettingsImpl();

        /// <summary>
        /// Returns a GUID for the utility from the command line, if one was provided, otherwise returns
        /// the GUID generated by the logging subsystem.
        /// </summary>
        /// <returns></returns>
        public static Guid GetJobID()
        {
            if (AppSettingsImpl.JobID.Initialized)
            {
                return new Guid(AppSettingsImpl.JobID.Value);
            }
            return Log.GUID;
        }

        /// <summary>
        /// The year and month of the file to download, in the form "YYYYMM"
        /// </summary>

        public static string FileYYYYMM = string.Empty;

    }
}
